# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Onmyoji_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 835)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Layout_Background = QtWidgets.QGridLayout()
        self.Layout_Background.setObjectName("Layout_Background")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.GB_ToolAndPara = QtWidgets.QGroupBox(self.centralwidget)
        self.GB_ToolAndPara.setTitle("")
        self.GB_ToolAndPara.setObjectName("GB_ToolAndPara")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.GB_ToolAndPara)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.GB_Tool = QtWidgets.QGroupBox(self.GB_ToolAndPara)
        self.GB_Tool.setObjectName("GB_Tool")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GB_Tool)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GB_JCKZ = QtWidgets.QGroupBox(self.GB_Tool)
        self.GB_JCKZ.setObjectName("GB_JCKZ")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GB_JCKZ)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bn_Stop = QtWidgets.QPushButton(self.GB_JCKZ)
        self.bn_Stop.setObjectName("bn_Stop")
        self.gridLayout_2.addWidget(self.bn_Stop, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.bn_Out = QtWidgets.QPushButton(self.GB_JCKZ)
        self.bn_Out.setObjectName("bn_Out")
        self.gridLayout_2.addWidget(self.bn_Out, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.bn_Start = QtWidgets.QPushButton(self.GB_JCKZ)
        self.bn_Start.setObjectName("bn_Start")
        self.gridLayout_2.addWidget(self.bn_Start, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.GB_JCKZ)
        self.GB_MSXZ = QtWidgets.QGroupBox(self.GB_Tool)
        self.GB_MSXZ.setObjectName("GB_MSXZ")
        self.gridLayout = QtWidgets.QGridLayout(self.GB_MSXZ)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.GB_MSXZ)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.cbx_KZMS = QtWidgets.QComboBox(self.GB_MSXZ)
        self.cbx_KZMS.setObjectName("cbx_KZMS")
        self.cbx_KZMS.addItem("")
        self.cbx_KZMS.addItem("")
        self.gridLayout.addWidget(self.cbx_KZMS, 2, 2, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(self.GB_MSXZ)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.GB_MSXZ)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cbx_FBLX = QtWidgets.QComboBox(self.GB_MSXZ)
        self.cbx_FBLX.setObjectName("cbx_FBLX")
        self.cbx_FBLX.addItem("")
        self.cbx_FBLX.addItem("")
        self.cbx_FBLX.addItem("")
        self.gridLayout.addWidget(self.cbx_FBLX, 0, 2, 1, 1, QtCore.Qt.AlignVCenter)
        self.cbx_ZDMS = QtWidgets.QComboBox(self.GB_MSXZ)
        self.cbx_ZDMS.setObjectName("cbx_ZDMS")
        self.cbx_ZDMS.addItem("")
        self.cbx_ZDMS.addItem("")
        self.cbx_ZDMS.addItem("")
        self.gridLayout.addWidget(self.cbx_ZDMS, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.GB_MSXZ)
        self.horizontalLayout_4.addWidget(self.GB_Tool)
        self.GB_Para = QtWidgets.QGroupBox(self.GB_ToolAndPara)
        self.GB_Para.setObjectName("GB_Para")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.GB_Para)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.GB_Para)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bn_SaveIni = QtWidgets.QPushButton(self.groupBox)
        self.bn_SaveIni.setObjectName("bn_SaveIni")
        self.horizontalLayout_8.addWidget(self.bn_SaveIni)
        self.bn_LoadIni = QtWidgets.QPushButton(self.groupBox)
        self.bn_LoadIni.setObjectName("bn_LoadIni")
        self.horizontalLayout_8.addWidget(self.bn_LoadIni)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.GB_Set = QtWidgets.QGroupBox(self.GB_Para)
        self.GB_Set.setObjectName("GB_Set")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.GB_Set)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.GB_Set)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ckb_Resize = QtWidgets.QCheckBox(self.tab)
        self.ckb_Resize.setChecked(False)
        self.ckb_Resize.setObjectName("ckb_Resize")
        self.gridLayout_3.addWidget(self.ckb_Resize, 0, 0, 1, 1)
        self.ckb_Rate = QtWidgets.QCheckBox(self.tab)
        self.ckb_Rate.setObjectName("ckb_Rate")
        self.gridLayout_3.addWidget(self.ckb_Rate, 4, 0, 1, 1)
        self.sil_Rate = QtWidgets.QSlider(self.tab)
        self.sil_Rate.setMinimum(1)
        self.sil_Rate.setMaximum(60)
        self.sil_Rate.setOrientation(QtCore.Qt.Horizontal)
        self.sil_Rate.setObjectName("sil_Rate")
        self.gridLayout_3.addWidget(self.sil_Rate, 4, 1, 1, 1)
        self.sil_Resize = QtWidgets.QSlider(self.tab)
        self.sil_Resize.setMinimum(20)
        self.sil_Resize.setMaximum(100)
        self.sil_Resize.setOrientation(QtCore.Qt.Horizontal)
        self.sil_Resize.setObjectName("sil_Resize")
        self.gridLayout_3.addWidget(self.sil_Resize, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.cbx_hwnd = QtWidgets.QComboBox(self.tab)
        self.cbx_hwnd.setObjectName("cbx_hwnd")
        self.gridLayout_3.addWidget(self.cbx_hwnd, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ckb_H11_Buff = QtWidgets.QCheckBox(self.tab_3)
        self.ckb_H11_Buff.setObjectName("ckb_H11_Buff")
        self.gridLayout_4.addWidget(self.ckb_H11_Buff, 0, 0, 1, 1)
        self.ckb_H11_TeamLeader = QtWidgets.QCheckBox(self.tab_3)
        self.ckb_H11_TeamLeader.setObjectName("ckb_H11_TeamLeader")
        self.gridLayout_4.addWidget(self.ckb_H11_TeamLeader, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.txt_H11_TeamNum = QtWidgets.QLineEdit(self.tab_3)
        self.txt_H11_TeamNum.setObjectName("txt_H11_TeamNum")
        self.gridLayout_4.addWidget(self.txt_H11_TeamNum, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.txt_H11_Times = QtWidgets.QLineEdit(self.tab_3)
        self.txt_H11_Times.setObjectName("txt_H11_Times")
        self.gridLayout_4.addWidget(self.txt_H11_Times, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_6.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.GB_Set)
        self.GB_Output = QtWidgets.QGroupBox(self.GB_Para)
        self.GB_Output.setObjectName("GB_Output")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.GB_Output)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txt_Result = QtWidgets.QTextBrowser(self.GB_Output)
        self.txt_Result.setObjectName("txt_Result")
        self.horizontalLayout_5.addWidget(self.txt_Result)
        self.verticalLayout_2.addWidget(self.GB_Output)
        self.horizontalLayout_4.addWidget(self.GB_Para)
        self.horizontalLayout_3.addWidget(self.GB_ToolAndPara)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.Layout_Background.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.lab_Img = QtWidgets.QLabel(self.centralwidget)
        self.lab_Img.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_Img.setObjectName("lab_Img")
        self.Layout_Background.addWidget(self.lab_Img, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.Layout_Background)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.bn_Exit = QtWidgets.QAction(MainWindow)
        self.bn_Exit.setObjectName("bn_Exit")
        self.menu.addAction(self.bn_Exit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GB_Tool.setTitle(_translate("MainWindow", "操作"))
        self.GB_JCKZ.setTitle(_translate("MainWindow", "进程控制"))
        self.bn_Stop.setText(_translate("MainWindow", "暂停"))
        self.bn_Out.setText(_translate("MainWindow", "退出"))
        self.bn_Start.setText(_translate("MainWindow", "开始"))
        self.GB_MSXZ.setTitle(_translate("MainWindow", "模式选择"))
        self.label_3.setText(_translate("MainWindow", "组队模式"))
        self.cbx_KZMS.setItemText(0, _translate("MainWindow", "前台"))
        self.cbx_KZMS.setItemText(1, _translate("MainWindow", "后台"))
        self.label_2.setText(_translate("MainWindow", "控制模式"))
        self.label.setText(_translate("MainWindow", "副本类型  "))
        self.cbx_FBLX.setItemText(0, _translate("MainWindow", "魂十"))
        self.cbx_FBLX.setItemText(1, _translate("MainWindow", "魂十一"))
        self.cbx_FBLX.setItemText(2, _translate("MainWindow", "探索"))
        self.cbx_ZDMS.setItemText(0, _translate("MainWindow", "单人"))
        self.cbx_ZDMS.setItemText(1, _translate("MainWindow", "双人"))
        self.cbx_ZDMS.setItemText(2, _translate("MainWindow", "多人"))
        self.GB_Para.setTitle(_translate("MainWindow", "参数"))
        self.bn_SaveIni.setText(_translate("MainWindow", "保存配置"))
        self.bn_LoadIni.setText(_translate("MainWindow", "加载配置"))
        self.GB_Set.setTitle(_translate("MainWindow", "设置"))
        self.ckb_Resize.setText(_translate("MainWindow", "缩放"))
        self.ckb_Rate.setText(_translate("MainWindow", "帧率"))
        self.label_5.setText(_translate("MainWindow", "游戏窗口："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "采集"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "魂十"))
        self.ckb_H11_Buff.setText(_translate("MainWindow", "开启御魂buff"))
        self.ckb_H11_TeamLeader.setText(_translate("MainWindow", "是否为队长"))
        self.label_4.setText(_translate("MainWindow", "   组队人数："))
        self.label_6.setText(_translate("MainWindow", "   挑战次数："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "魂十一"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "探索"))
        self.GB_Output.setTitle(_translate("MainWindow", "输出"))
        self.lab_Img.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/背景/back.jpg\"/></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.bn_Exit.setText(_translate("MainWindow", "退出"))

import Onmyoji_Rcc_rc
